export const LABELS = {
  theBrand:
    "Nel tempo il marchio si é consolidato grazie a varie collaborazione e il susseguirsi dellecollezioni stagionali. Infatti, parallelamente al progetto con le scuole, portiamo avanti la parte legata al brand.",
  smbForSchools:
    "Saint Mary Boulevard for Schools nasce dal bisogno delle scuole superiori di avere un proprio vestiario d’istituto che unisca qualitá e stile. Nel 2016 tre scuole Veronesi si rivolsero a noi per questo tipo di servizio e da allora portiamo avanti questo lavoro giorno dopo giorno. Il nostro obbiettivo é quello di arrivare ad un prodotto finito tale da poter essere indossato sia nelle mura scolastiche ma soprattutto nel quotidiano. Infatti i ragazzi che acquistano i nostri prodotti li indossano quotidianamente rendendo cosi l’abbigliamento scolastico piú versatile.",
  graphics:
    "Uno degli aspetti piú importanti per noi é proprio la cura di grafiche e loghi. Per questo motivo, nel caso la vostra scuola non avesse un logo o ne volesse uno particolare per il merchandising, il nostro team di grafici sará sempre a vostra disposizione per realizzare le vostre idee. Il servizio é gratuito e senza spese extra premettendovi di valorizzare l’identitá dell’istituto,rendendo cosí il logo un segno distintivo.",
  productsAndColors:
    "Per realizzare un buon lavoro la scelta del prodotto adeguato é fondamentale. Infatti i nostri prodotti dispongono di una grande gamma cromatica, necessaria per esaudire le vostre esigenze. La scelta che vi offriamo non si limita solo ai colori ma bensí ai prodotti stessi. Infatti oltre alle piú classiche t-shirt e hoodie proponiamo diversi capi di abbigliamento: polo, cappellini, berretti invernali, pantaloncini sportivi, maglie a maniche lunghe, giacche e zaini. Per non farsimancare niente avrete la possibilitá di realizare diversi gadget: borraccie per un tocco piu green,tazze, portachiavi, adesivi, penne e molto altro!",
  delivery:
    "L’organizzazione del ritiro degli ordini passa attraverso i moduli, consegnati singolarmente ad ogni classe. Infatti vi forniremo un modulo contenente il prototipo dei capi, i colori e le taglie disponibili.Ogni singola classe dovrá compilarlo in base alle richieste dei propri studenti. Inoltre vi é la possibilitá di svolgere questa operazione interamente online, tramite piattaforme da noi fornite per la raccolta degli ordini. Una volta raccolti i moduli ne verrá formato uno unico cosi da ottenere il numero totale degli ordini. In seguito, ordinati e prodotti i capi, provvederemo alla consegna presso il vostro istituto.Se la vostra scuola si trova a Verona o provincia la cosegna la effetueremo personalmente, altrimenti con corrieri espressi con spedizione veloce in 24/48h.",
};
